remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Pure PHP DoH Client
description: Retrieve DNS records via DoH in PHP
show_downloads: true
github:
  zip_url: https://github.com/LJPc-solutions/Pure-PHP-DoH-Client/archive/refs/heads/master.zip
